#!/usr/bin/env python3
"""Generate tool-specific agent definitions from tool-neutral role specs (plan §8).

Inputs:  skills/roles/<role>/role.yaml + ROLE.md
         skills/workflow/adlc-conductor/SKILL.md (workflow entry point, plan v3.1 §4.14)
Outputs: dist/claude/.claude/agents/<role>.md
         dist/copilot/.github/agents/<role>.agent.md
         dist/claude/settings.roles.json   (per-role permission deny fragments)
         dist/claude/.claude/commands/adlc.md      (Claude Code `/adlc` command)
         dist/copilot/.github/prompts/adlc.prompt.md (Copilot Chat `/adlc` prompt file)

role.yaml is written in the JSON-compatible subset of YAML (JSON is valid YAML 1.2), so this
script stays stdlib-only and parses it with `json`. Keep role.yaml strict JSON.

Usage:
    python skills/roles/scripts/generate_agents.py           # write dist/
    python skills/roles/scripts/generate_agents.py --check   # exit 1 if dist/ is stale
"""
from __future__ import annotations

import argparse
import json
import posixpath
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
GENERATED_NOTE = "GENERATED by skills/roles/scripts/generate_agents.py from skills/roles/{role}/ — do not edit."

REQUIRED_KEYS = (
    "name", "description", "phase", "model_tier", "model_family_constraint", "operation_classes",
    "can_read", "can_modify", "denied_paths", "allowed_tools", "mcp_servers", "can_set", "never_set",
    "skills_required", "handoff_outputs",
)
AGENT_SETTABLE = {"REVIEWED", "READY_FOR_APPROVAL"}
MUST_NEVER_SET = {"APPROVED", "VERIFIED", "INTEGRATED", "RELEASED", "PLAN_APPROVED", "READY", "DONE", "ACCEPTED"}
AGENT_OPERATION_CLASSES = {"READ", "WORKSPACE_WRITE", "REPO_WRITE"}

CLAUDE_TOOLS = {
    "read": ["Read"],
    "search": ["Grep", "Glob"],
    "edit": ["Edit"],
    "write": ["Write"],
    "bash": ["Bash"],
    "test-run": ["Bash"],
}
COPILOT_TOOLS = {
    "read": ["read"],
    "search": ["search"],
    "edit": ["edit"],
    "write": ["edit"],
    "bash": ["execute"],
    "test-run": ["execute"],
}
CLAUDE_MODELS = {"strong": "opus", "default": "sonnet", "fast": "haiku"}

LINK_RE = re.compile(r"\]\(([^)\s]+)\)")


class RoleSpecError(ValueError):
    pass


def load_roles(roles_dir: Path) -> list[dict]:
    roles = []
    for spec_path in sorted(roles_dir.glob("*/role.yaml")):
        spec = json.loads(spec_path.read_text(encoding="utf-8"))
        body_path = spec_path.with_name("ROLE.md")
        if not body_path.exists():
            raise RoleSpecError(f"{spec_path.parent.name}: missing ROLE.md")
        spec["_body"] = body_path.read_text(encoding="utf-8")
        validate(spec, spec_path.parent.name)
        roles.append(spec)
    if not roles:
        raise RoleSpecError(f"no role.yaml files under {roles_dir}")
    return roles


def validate(spec: dict, dirname: str) -> None:
    missing = [k for k in REQUIRED_KEYS if k not in spec]
    if missing:
        raise RoleSpecError(f"{dirname}: missing keys {missing}")
    if spec["name"] != dirname:
        raise RoleSpecError(f"{dirname}: name {spec['name']!r} does not match directory")
    bad_set = {c["value"] for c in spec["can_set"]} - AGENT_SETTABLE
    if bad_set:
        raise RoleSpecError(f"{dirname}: agents may never set {sorted(bad_set)}")
    absent = MUST_NEVER_SET - set(spec["never_set"])
    if absent:
        raise RoleSpecError(f"{dirname}: never_set must include {sorted(absent)}")
    bad_ops = set(spec["operation_classes"]) - AGENT_OPERATION_CLASSES
    if bad_ops:
        raise RoleSpecError(f"{dirname}: operation classes {sorted(bad_ops)} are CI/server-only")
    for tool in spec["allowed_tools"]:
        if not (tool in CLAUDE_TOOLS or tool.startswith("mcp:")):
            raise RoleSpecError(f"{dirname}: unknown abstract tool {tool!r}")


def _split_mcp(tool: str) -> tuple[str, str]:
    server, _, name = tool[len("mcp:"):].partition(".")
    if not server or not name:
        raise RoleSpecError(f"malformed MCP tool {tool!r}; expected mcp:<server>.<tool>")
    return server, name


def map_tools(tools: list[str], target: str) -> list[str]:
    table = CLAUDE_TOOLS if target == "claude" else COPILOT_TOOLS
    out: list[str] = []
    for tool in tools:
        if tool.startswith("mcp:"):
            server, name = _split_mcp(tool)
            mapped = [f"mcp__{server}__{name}" if target == "claude" else f"{server}/{name}"]
        else:
            mapped = table[tool]
        for m in mapped:
            if m not in out:
                out.append(m)
    return out


def rewrite_links(body: str, role: str, base: str | None = None) -> str:
    """Relative links in ROLE.md are relative to skills/roles/<role>/; make them repo-relative."""
    base = base or f"skills/roles/{role}"

    def fix(match: re.Match) -> str:
        target = match.group(1)
        if re.match(r"^[a-z]+:|^#|^/", target):
            return match.group(0)
        return f"]({posixpath.normpath(posixpath.join(base, target))})"

    return LINK_RE.sub(fix, body)


def _bullets(items) -> str:
    return "\n".join(f"- `{i}`" for i in items) or "- (none)"


def scope_section(spec: dict) -> str:
    can_set = [
        f"{c['value']} ({c['scope']}" + (f"; {'/'.join(c['verdicts'])}" if "verdicts" in c else "") + ")"
        for c in spec["can_set"]
    ]
    return "\n".join([
        "## Scope (generated from role.yaml)",
        "",
        f"- Phase: {spec['phase']}",
        f"- Model family constraint: {spec['model_family_constraint']}",
        f"- Operation classes: {', '.join(spec['operation_classes'])}",
        *([f"- Rule of Two: {spec['rule_of_two']}"] if spec.get("rule_of_two") else []),
        "",
        "Can read:", _bullets(spec["can_read"]), "",
        "Can modify:", _bullets(spec["can_modify"]), "",
        "Denied (read):", _bullets(spec["denied_paths"]["read"]), "",
        "Denied (write):", _bullets(spec["denied_paths"]["write"]), "",
        "Can set:", _bullets(can_set), "",
        "Never sets:", _bullets(spec["never_set"]), "",
        "Required skills:", _bullets(spec["skills_required"]), "",
        "Handoff outputs:", _bullets(spec["handoff_outputs"]), "",
    ])


def _frontmatter(fields: list[tuple[str, object]]) -> str:
    lines = ["---"]
    for key, value in fields:
        if isinstance(value, list):
            lines.append(f"{key}: [{', '.join(json.dumps(v) for v in value)}]")
        else:
            lines.append(f"{key}: {json.dumps(value)}")
    lines.append("---")
    return "\n".join(lines)


def _document(spec: dict, frontmatter: str) -> str:
    note = GENERATED_NOTE.format(role=spec["name"])
    body = rewrite_links(spec["_body"], spec["name"]).rstrip()
    return f"{frontmatter}\n\n<!-- {note} -->\n\n{body}\n\n{scope_section(spec)}"


def render_claude(spec: dict) -> str:
    fm = _frontmatter([
        ("name", spec["name"]),
        ("description", spec["description"]),
        ("tools", ", ".join(map_tools(spec["allowed_tools"], "claude"))),
        ("model", CLAUDE_MODELS[spec["model_tier"]]),
    ])
    return _document(spec, fm)


def render_copilot(spec: dict) -> str:
    fields: list[tuple[str, object]] = [
        ("name", spec["name"]),
        ("description", spec["description"]),
        ("tools", map_tools(spec["allowed_tools"], "copilot")),
    ]
    if spec.get("copilot_model"):
        fields.append(("model", spec["copilot_model"]))
    return _document(spec, _frontmatter(fields))


def render_settings(roles: list[dict]) -> str:
    out: dict = {
        "_generated": GENERATED_NOTE.format(role="*"),
        "_note": (
            "Per-role deny fragments. Claude Code settings apply per session, so launch each role's "
            "session with its fragment merged in (e.g. `claude --settings <fragment>`). Control-file "
            "denial is NOT here: it is enforced org-wide by managed settings (skills/enforcement/)."
        ),
        "roles": {},
    }
    for spec in roles:
        deny: list[str] = []
        for glob in spec["denied_paths"]["read"]:
            deny.append(f"Read({glob})")
        for glob in spec["denied_paths"]["write"]:
            if glob.startswith("$ref:"):
                continue
            deny += [f"Edit({glob})", f"Write({glob})"]
        if "bash" not in spec["allowed_tools"] and "test-run" not in spec["allowed_tools"]:
            deny.append("Bash")
        refs = [g[len("$ref:"):] for g in spec["denied_paths"]["write"] if g.startswith("$ref:")]
        out["roles"][spec["name"]] = {
            "permissions": {"deny": deny},
            "control_file_policy": refs,
        }
    return json.dumps(out, indent=2) + "\n"


ENTRY_NOTE = "GENERATED by skills/roles/scripts/generate_agents.py from skills/workflow/adlc-conductor/SKILL.md — do not edit."
ENTRY_BASE = "skills/workflow/adlc-conductor"
ARGUMENT_HINT = "[from <stage> to <stage> | only <stage> | resume [from <stage>]] [ST-n] [docs or export paths]"


def _split_frontmatter(text: str) -> tuple[dict, str]:
    """Minimal SKILL.md frontmatter split: returns ({name, description}, body)."""
    m = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.S)
    if not m:
        raise RoleSpecError("adlc-conductor SKILL.md has no frontmatter")
    meta = {}
    for line in m.group(1).splitlines():
        km = re.match(r"^(name|description):\s*(.*)$", line)
        if km:
            meta[km.group(1)] = km.group(2).strip().strip('"')
    return meta, m.group(2)


def render_entry_points(conductor: Path) -> dict[str, str]:
    """`/adlc` for Claude Code (custom command) and Copilot Chat (prompt file)."""
    meta, body = _split_frontmatter(conductor.read_text(encoding="utf-8"))
    body = rewrite_links(body, "", base=ENTRY_BASE).strip()
    description = "Run ADLC work from any stage to any stage (INTAKE → … → RELEASE) with every gate, then checkpoint."
    claude = "\n".join([
        _frontmatter([("description", description), ("argument-hint", ARGUMENT_HINT)]),
        "",
        f"<!-- {ENTRY_NOTE} -->",
        "",
        "Run the ADLC conductor for this request: **$ARGUMENTS**",
        "",
        f"Follow `{ENTRY_BASE}/SKILL.md` exactly (reproduced below). Start with workspace resolution and stage "
        "preflight; never skip a gate between the start and end stage.",
        "",
        body,
    ]) + "\n"
    copilot = "\n".join([
        _frontmatter([("description", description), ("agent", "agent")]),
        "",
        f"<!-- {ENTRY_NOTE} -->",
        "",
        "Run the ADLC conductor for this request: **${input:request:from <stage> to <stage>, only <stage>, or resume}**",
        "",
        f"Follow `{ENTRY_BASE}/SKILL.md` exactly (reproduced below). Start with workspace resolution and stage "
        "preflight; never skip a gate between the start and end stage.",
        "",
        body,
    ]) + "\n"
    return {"claude/.claude/commands/adlc.md": claude, "copilot/.github/prompts/adlc.prompt.md": copilot}


def build(roles_dir: Path, workflow_dir: Path | None = None) -> dict[str, str]:
    roles = load_roles(roles_dir)
    files = {}
    for spec in roles:
        files[f"claude/.claude/agents/{spec['name']}.md"] = render_claude(spec) + "\n"
        files[f"copilot/.github/agents/{spec['name']}.agent.md"] = render_copilot(spec) + "\n"
    files["claude/settings.roles.json"] = render_settings(roles)
    conductor = (workflow_dir or roles_dir.parent / "workflow") / "adlc-conductor" / "SKILL.md"
    if conductor.is_file():
        files.update(render_entry_points(conductor))
    return files


def _existing_generated(dist: Path) -> set[str]:
    found = set()
    for pattern in ("claude/.claude/agents/*.md", "copilot/.github/agents/*.agent.md", "claude/settings.roles.json",
                    "claude/.claude/commands/*.md", "copilot/.github/prompts/*.prompt.md"):
        found |= {p.relative_to(dist).as_posix() for p in dist.glob(pattern)}
    return found


def check(files: dict[str, str], dist: Path) -> list[str]:
    problems = []
    for rel, content in files.items():
        path = dist / rel
        if not path.exists():
            problems.append(f"missing: {rel}")
        elif path.read_text(encoding="utf-8") != content:
            problems.append(f"stale: {rel}")
    for rel in sorted(_existing_generated(dist) - set(files)):
        problems.append(f"orphaned: {rel}")
    return problems


def write(files: dict[str, str], dist: Path) -> None:
    for rel in _existing_generated(dist) - set(files):
        (dist / rel).unlink()
    for rel, content in files.items():
        path = dist / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--roles-dir", type=Path, default=REPO_ROOT / "skills" / "roles")
    parser.add_argument("--dist", type=Path, default=REPO_ROOT / "dist")
    parser.add_argument("--check", action="store_true", help="exit 1 if dist/ differs from what would be generated")
    args = parser.parse_args(argv)

    try:
        files = build(args.roles_dir)
    except (RoleSpecError, json.JSONDecodeError) as exc:
        print(json.dumps({"ok": False, "error": str(exc)}))
        return 2

    if args.check:
        problems = check(files, args.dist)
        print(json.dumps({"ok": not problems, "problems": problems}, indent=2))
        return 1 if problems else 0

    write(files, args.dist)
    print(json.dumps({"ok": True, "written": sorted(files)}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
