#!/usr/bin/env python3
"""Bootstrap a new project for ADLC: create plans/, workspace manifest, and intake REQ.

Creates the minimum scaffolding so that `/adlc from INTAKE to DESIGN` does not hit a
cold-start BLOCK. Idempotent — skips files that already exist.

Usage:
    python bootstrap_project.py --system acme --title "Add payment processing"
    python bootstrap_project.py --system acme --title "Add payments" --statement "..."
    python bootstrap_project.py --check          # exit 0 if already bootstrapped

Exit codes: 0 success or already bootstrapped · 1 partial (some files exist) · 2 bad input.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

_skills_root_env = os.environ.get("ADLC_SKILLS_ROOT")
_workflow = Path(_skills_root_env, "skills", "workflow").resolve() if _skills_root_env else Path(__file__).resolve().parents[2]


PLANS_DIRS = [
    "plans/requirements",
    "plans/epics",
    "plans/stories",
    "plans/milestones",
    "plans/test-designs",
    "plans/intake",
]

MANIFEST_NAME = "adlc.workspace.yaml"


def _manifest_content(system: str, repo_name: str) -> str:
    return json.dumps({
        "version": 1,
        "system": system,
        "draft": True,
        "repos": [
            {"name": repo_name, "roles": ["app", "planning"], "path": "."}
        ],
        "notes": "Auto-generated by bootstrap_project.py. Review and set draft:false."
    }, indent=2)


def _requirement_content(req_id: str, title: str, statement: str, requested_by: str) -> str:
    return json.dumps({
        "id": req_id,
        "title": title,
        "statement": statement,
        "requested_by": requested_by,
        "source_refs": [
            {"ref": "user-statement:bootstrap", "trust_level": "EXTERNAL_UNSTRUCTURED",
             "note": "Initial requirement from bootstrap — attach real source refs before APPROVAL."}
        ],
        "business_outcome": "To be refined during INTAKE stage."
    }, indent=2)


def find_git_root(start: Path) -> Path | None:
    p = start.resolve()
    while p != p.parent:
        if (p / ".git").exists():
            return p
        p = p.parent
    return None


def repo_name_from_path(path: Path) -> str:
    return path.name.replace(" ", "-").lower() or "project"


def bootstrap(root: Path, system: str, title: str | None = None,
              statement: str | None = None, requested_by: str = "human:user") -> dict:
    created = []
    skipped = []

    for d in PLANS_DIRS:
        dp = root / d
        if dp.exists():
            skipped.append(d)
        else:
            dp.mkdir(parents=True, exist_ok=True)
            (dp / ".gitkeep").write_text("", encoding="utf-8")
            created.append(d)

    manifest_path = root / MANIFEST_NAME
    if manifest_path.exists():
        skipped.append(MANIFEST_NAME)
    else:
        repo_name = repo_name_from_path(root)
        manifest_path.write_text(_manifest_content(system, repo_name), encoding="utf-8")
        created.append(MANIFEST_NAME)

    if title:
        req_path = root / "plans" / "intake" / "REQ-1.json"
        if req_path.exists():
            skipped.append("plans/intake/REQ-1.json")
        else:
            stmt = statement or f"Implement: {title}"
            req_path.write_text(
                _requirement_content("REQ-1", title, stmt, requested_by),
                encoding="utf-8"
            )
            created.append("plans/intake/REQ-1.json")

    adlc_dir = root / ".adlc"
    if not adlc_dir.exists():
        adlc_dir.mkdir(parents=True, exist_ok=True)
        created.append(".adlc/")

    return {"created": created, "skipped": skipped}


def check_bootstrapped(root: Path) -> bool:
    required = [root / "plans", root / MANIFEST_NAME]
    return all(p.exists() for p in required)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", type=Path, default=Path.cwd(),
                        help="Project root (default: cwd)")
    parser.add_argument("--system", default=None,
                        help="System name for the workspace manifest (default: directory name)")
    parser.add_argument("--title", default=None,
                        help="Title for an initial REQ-1 in plans/intake/")
    parser.add_argument("--statement", default=None,
                        help="Requirement statement (defaults to 'Implement: <title>')")
    parser.add_argument("--requested-by", default="human:user",
                        help="Who requested the requirement")
    parser.add_argument("--check", action="store_true",
                        help="Exit 0 if bootstrapped, 1 if not")
    args = parser.parse_args(argv)

    root = args.root.resolve()
    git_root = find_git_root(root)
    if git_root:
        root = git_root

    if args.check:
        ok = check_bootstrapped(root)
        print(json.dumps({"bootstrapped": ok, "root": str(root)}))
        return 0 if ok else 1

    system = args.system or repo_name_from_path(root)
    result = bootstrap(root, system, args.title, args.statement, args.requested_by)
    result["root"] = str(root)
    result["ok"] = True
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
