#!/usr/bin/env python3
"""Generate the Claude Code managed-settings template from control-file-paths.json.

Every control glob becomes `Edit(<glob>)` and `Write(<glob>)` deny rules (Edit rules cover
all built-in file-editing tools). Hooks come from hooks/registration/claude-code-hooks.json.

Usage:
  python generate_deny_list.py              # rewrite templates/claude-code-managed-settings.json
  python generate_deny_list.py --check      # exit 1 if the template is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "lib"))
import adlc_enforcement as ae  # noqa: E402

TEMPLATE = HERE / "templates" / "claude-code-managed-settings.json"
HOOKS = HERE.parent / "hooks" / "registration" / "claude-code-hooks.json"


def deny_rules(globs: list[str]) -> list[str]:
    rules: list[str] = []
    for g in globs:
        rules += [f"Edit({g})", f"Write({g})"]
    return rules


def build(control_paths: Path | None = None) -> dict:
    globs = ae.load_control_globs(control_paths)
    hooks = json.loads(HOOKS.read_text(encoding="utf-8"))["hooks"]
    return {
        "$comment": (
            "GENERATED by skills/enforcement/managed-settings/generate_deny_list.py from "
            "control-file-paths.json — do not hand-edit. Deploy to the OS managed-settings "
            "location (admin-owned); replace {{ADLC_ENFORCEMENT_DIR}}."
        ),
        "permissions": {
            "deny": deny_rules(globs),
            "disableBypassPermissionsMode": "disable",
        },
        "allowManagedHooksOnly": True,
        "allowManagedPermissionRulesOnly": True,
        "hooks": hooks,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if the template is out of date")
    ap.add_argument("--control-paths", type=Path)
    args = ap.parse_args()
    rendered = json.dumps(build(args.control_paths), indent=2) + "\n"
    if args.check:
        current = TEMPLATE.read_text(encoding="utf-8") if TEMPLATE.exists() else ""
        ok = current == rendered
        print(json.dumps({"check": "managed-settings-template-current", "ok": ok}))
        return 0 if ok else 1
    TEMPLATE.parent.mkdir(parents=True, exist_ok=True)
    TEMPLATE.write_text(rendered, encoding="utf-8")
    print(json.dumps({"written": str(TEMPLATE), "deny_rules": len(build(args.control_paths)["permissions"]["deny"])}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
